version: '2'

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    user: root
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus:/prometheus
    command:
      - '--storage.tsdb.path=/prometheus'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention=90d'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
      - pushgateway:pushgateway
    networks:
      - back-tier

  node-exporter:
    container_name: node-exporter
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    restart: on-failure:5
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc
      - /sys:/host/sysfs
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sysfs'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    expose:
      - 9100
    networks:
      - back-tier

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:4.5.2
    links:
      - prometheus:prometheus
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    ports:
      - 9091:9091
    networks:
      - back-tier
